### ISSUE TITLE
How do we use the config files?

### ISSUE THREAD

**Issue by anevins12** [lloydi/PolyPane-Config#1]
I'm very new to PolyPane having just installed it after seeing your LinkedIn post. 

I've downloaded it, set it up, but don't see an option to import your `.ppws` files. Perhaps I'm missing the point here and I'm not meant to import them.

Can you help enlighten me on what I'm doing wrong?

**Comment by lloydi** [comment]
I have added some 'How to' steps to the ReadMe :)
